#!/usr/bin/env python3

from random import randint


def list_process(expect_list):

    from re import sub
    ucas_list, temp_list, first_names_list, surnames_list, names_initials = ([] for i in range(5))
    temp_string = ""
    for k in expect_list:
        ucas_list.append(k[:8])
        temp_list.append(k[9:])
    for m in temp_list:
        surnames_list.append(m[:m.index(",")])
        first_names_list.append(m[m.index(",")+1:])
    surnames_list = [element.lower() for element in surnames_list]
    for x in surnames_list:
        new_string = sub(r'[^a-zA-Z]', '', x)
        surnames_list[surnames_list.index(x)] = new_string
    for element in first_names_list:
        for c in range(0, len(element)):
            if element[c] == ' ':
                temp_string += element[c+1].lower() + '.'
            if c == len(element)-1:
                names_initials.append(temp_string)
                temp_string = ""
    return ucas_list, surnames_list, names_initials


if __name__ == "__main__":
    with open("students.txt", "r") as my_file:
        data_into_list = my_file.readlines()
    my_list = list_process(data_into_list)
    final_list = []
    for n in range(0, len(my_list[0][:])):
        rand_number = ""
        for num in range(4):
            rand_number += str(randint(0, 9))
        final_list.append(my_list[0][n] + " " + my_list[2][n] + my_list[1][n] + rand_number + "@poppleton.ac.uk")
    for n in final_list:
        print(n)
